### ISSUE TITLE
축제 바텀시트의 온보딩 툴팁의 화살표 방향이 위로 향하고 있는 문제 

### ISSUE THREAD

**Issue by easyhooon** [Project-Unifest/unifest-android#111]
![image](https://github.com/Project-Unifest/unifest-android/assets/51016231/555797b7-7af9-42f7-873c-20f22dc2cec3)

ArrowOrientation 을 Bottom 으로 지정했으나, Top 으로 설정되고 있음

**Comment by easyhooon** [comment]
https://github.com/skydoves/Balloon/issues/627

**Comment by skydoves** [comment]
Hey @easyhooon, sorry for the late response. Have you fixed this issue using your own solution?
