### ISSUE TITLE
[fix] 인트로 화면 학교 정보 못받아오는 문제 수정

### ISSUE THREAD

**Issue by wjdtkdgns777** [Project-Unifest/unifest-android#243]
흠.. 서버에서 어디가 바뀐건지 리팩토링 중 어딘가 바뀐건지 학교정보를 못가져오는중
라이브는 문제없음

**Comment by easyhooon** [comment]
kotlinx.serialization.json.internal.JsonDecodingException: Unexpected JSON token at offset 221: Expected beginning of the string, but got [ at path: $.data[0].beginDate
JSON input: .....stivalName":"대동제","beginDate":[2024,5,21],"endDate":[2024,5,.....

API 규격이 바뀐거 같네요 beginDate 와 endDate 가 String type 이었는데 list 로 변경된 것 같습니다.

**Comment by easyhooon** [comment]
서버 개발자분께서 해결해주셨습니다
