### ISSUE TITLE
Map에서 BoothDetailScreen으로 화면 전환시 하단에 검은색으로 가려지는 문제

### ISSUE THREAD

**Issue by wjdtkdgns777** [Project-Unifest/unifest-android#52]
https://github.com/Project-Unifest/unifest-android/assets/60922290/7d8de7a3-1fed-48d8-828c-c21632d7a0db

**Comment by easyhooon** [comment]
지도가 바텀 네비게이션 바 아래까지는 공간을 차지 하지 않는데, 화면을 이동하면서 바텀 네비게이션 바가 hide 될 때, 그 뒤의 색상이 보이는 것 같네요 MainScreen 내에 Scaffold 의 ContainerColor 를 White 색상으로 부여는 해놨는데 왜 검정색으로 보이는지,,
