### ISSUE TITLE
Map화면에서 BottomSheet의 TextField 커서 위치가 어색한 문제

### ISSUE THREAD

**Issue by wjdtkdgns777** [Project-Unifest/unifest-android#56]
![KakaoTalk_20240410_131744286](https://github.com/Project-Unifest/unifest-android/assets/60922290/aa1a6688-b0d1-4f49-b132-37418ed270d3)

텍스트필드의 커서가 보다 위에 표시됩니다. 
바텀시트에서 입력중 텍스트필드를 눌러 커서를 등장하면 재현할수 있습니다.

**Comment by easyhooon** [comment]
개같은 bottomsheet..

**Comment by easyhooon** [comment]
#62
