### ISSUE TITLE
Intro 화면 의 탭 간격 축소 및 탭 하단 Swipe 지원

### ISSUE THREAD

**Issue by wjdtkdgns777** [Project-Unifest/unifest-android#79]
![KakaoTalk_20240416_004126995](https://github.com/Project-Unifest/unifest-android/assets/60922290/32cddca3-6cfa-4c4d-ae2f-562574388fba)

디자인 스펙에 비해 기본 탭 간격이 큰 상태인데,
ScrollableTabRow에 탭 간격 속성이 없어 커스텀이 필요
https://stackoverflow.com/questions/76503595/reduce-spacing-between-scrollable-tabs-in-compose

**Comment by easyhooon** [comment]
탭 뿐만 아니라 화면 하단 리스트화면을 swipe 해도 다음 탭으로 넘어갈 수 있도록 지원

**Comment by easyhooon** [comment]
reference)
치지직 요일별 시리즈

**Comment by easyhooon** [comment]
https://medium.com/@gautier.louis/tab-row-made-easy-in-jetpack-compose-8eaa5a602744
