### ISSUE TITLE
홈 화면의 캘린더가 상태를 유지하지 못하는 버그

### ISSUE THREAD

**Issue by wjdtkdgns777** [Project-Unifest/unifest-android#98]
https://github.com/Project-Unifest/unifest-android/assets/60922290/1d359782-82dd-4f77-a27d-628de7cedb14

동영상으로는 안느껴지실수도 있는데, 캘린더가 보이지 않는 화면까지 스크롤했다가 다시 캘린더가 보이도록 위로 스크롤해 올릴때,

캘린더가 불려오는 시간이 있는지 0.5초정도 미세하게 멈추며 버벅이며 동작을 합니다.

또 weekmode였다가도 스크롤해 안보이던 상황에서 다시 올려보이게하면 monthmode로 바뀌어있습니다.

**Comment by easyhooon** [comment]
weekmode -> monthmode 같은 경우는 recomposition 관련해서 초기화되었을 가능성을 의심해볼수있고, 스크롤 버벅임 현상은 compose debug 에서는 어쩔수없는거같아서 release 에서 한번 확인해봐야할것같네요

**Comment by easyhooon** [comment]
> 또 weekmode였다가도 스크롤해 안보이던 상황에서 다시 올려보이게하면 monthmode로 바뀌어있습니다.

이거는 전 재현하지 못했습니다.
